[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/api/upload"
  to = "/.netlify/functions/upload"
  status = 200

[[redirects]]
  from = "/api/analyze"
  to = "/.netlify/functions/analyze"
  status = 200

[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/health"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_URL = ""
  VITE_APP_TITLE = "FaceScore AI"
  VITE_MAX_FILE_SIZE = "10485760"

[context.deploy-preview.environment]
  VITE_API_URL = "http://113.153.91.53:3001"
  VITE_APP_TITLE = "FaceScore AI (Preview)"
  VITE_MAX_FILE_SIZE = "10485760"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"